### ISSUE TITLE
most debian repos are empty

### ISSUE THREAD

**Issue by DrupaListo-com** [Tox/tox.chat#101] opened 2016-04-14 11:43 UTC
Here is a list of Packages files in deb repos that are empty (empty ones have 0 in front, the last ones are NOT empty and the number in front is the size in bytes of the file..):

0       ./debian/dists/nightly/debug/binary-amd64/Packages
0       ./debian/dists/nightly/debug/binary-armel/Packages
0       ./debian/dists/nightly/debug/binary-armhf/Packages
0       ./debian/dists/nightly/debug/binary-i386/Packages
0       ./debian/dists/nightly/jessie/binary-armel/Packages
0       ./debian/dists/nightly/jessie/binary-armhf/Packages
0       ./debian/dists/nightly/release/binary-armel/Packages
0       ./debian/dists/nightly/release/binary-armhf/Packages
0       ./debian/dists/nightly/sid/binary-armel/Packages
0       ./debian/dists/nightly/sid/binary-armhf/Packages
0       ./debian/dists/nightly/stretch/binary-armel/Packages
0       ./debian/dists/nightly/stretch/binary-armhf/Packages
0       ./debian/dists/nightly/trusty/binary-amd64/Packages
0       ./debian/dists/nightly/trusty/binary-armel/Packages
0       ./debian/dists/nightly/trusty/binary-armhf/Packages
0       ./debian/dists/nightly/trusty/binary-i386/Packages
0       ./debian/dists/nightly/vivid/binary-armel/Packages
0       ./debian/dists/nightly/vivid/binary-armhf/Packages
0       ./debian/dists/nightly/wheezy/binary-amd64/Packages
0       ./debian/dists/nightly/wheezy/binary-armel/Packages
0       ./debian/dists/nightly/wheezy/binary-armhf/Packages
0       ./debian/dists/nightly/wheezy/binary-i386/Packages
0       ./debian/dists/nightly/wily/binary-armel/Packages
0       ./debian/dists/nightly/wily/binary-armhf/Packages
0       ./debian/dists/nightly/xenial/binary-amd64/Packages
0       ./debian/dists/nightly/xenial/binary-armel/Packages
0       ./debian/dists/nightly/xenial/binary-armhf/Packages
0       ./debian/dists/nightly/xenial/binary-i386/Packages
0       ./debian/dists/stable/jessie/binary-amd64/Packages
0       ./debian/dists/stable/jessie/binary-armel/Packages
0       ./debian/dists/stable/jessie/binary-armhf/Packages
0       ./debian/dists/stable/jessie/binary-i386/Packages
0       ./debian/dists/stable/release/binary-amd64/Packages
0       ./debian/dists/stable/release/binary-armel/Packages
0       ./debian/dists/stable/release/binary-armhf/Packages
0       ./debian/dists/stable/release/binary-i386/Packages
0       ./debian/dists/stable/sid/binary-amd64/Packages
0       ./debian/dists/stable/sid/binary-armel/Packages
0       ./debian/dists/stable/sid/binary-armhf/Packages
0       ./debian/dists/stable/sid/binary-i386/Packages
0       ./debian/dists/stable/stretch/binary-amd64/Packages
0       ./debian/dists/stable/stretch/binary-armel/Packages
0       ./debian/dists/stable/stretch/binary-armhf/Packages
0       ./debian/dists/stable/stretch/binary-i386/Packages
0       ./debian/dists/stable/trusty/binary-amd64/Packages
0       ./debian/dists/stable/trusty/binary-armel/Packages
0       ./debian/dists/stable/trusty/binary-armhf/Packages
0       ./debian/dists/stable/trusty/binary-i386/Packages
0       ./debian/dists/stable/vivid/binary-amd64/Packages
0       ./debian/dists/stable/vivid/binary-armel/Packages
0       ./debian/dists/stable/vivid/binary-armhf/Packages
0       ./debian/dists/stable/vivid/binary-i386/Packages
0       ./debian/dists/stable/wheezy/binary-amd64/Packages
0       ./debian/dists/stable/wheezy/binary-armel/Packages
0       ./debian/dists/stable/wheezy/binary-armhf/Packages
0       ./debian/dists/stable/wheezy/binary-i386/Packages
0       ./debian/dists/stable/wily/binary-amd64/Packages
0       ./debian/dists/stable/wily/binary-armel/Packages
0       ./debian/dists/stable/wily/binary-armhf/Packages
0       ./debian/dists/stable/wily/binary-i386/Packages
0       ./debian/dists/stable/xenial/binary-amd64/Packages
0       ./debian/dists/stable/xenial/binary-armel/Packages
0       ./debian/dists/stable/xenial/binary-armhf/Packages
0       ./debian/dists/stable/xenial/binary-i386/Packages
4       ./debian/dists/nightly/release/binary-amd64/Packages
4       ./debian/dists/nightly/release/binary-i386/Packages
12      ./debian/dists/nightly/jessie/binary-amd64/Packages
12      ./debian/dists/nightly/jessie/binary-i386/Packages
12      ./debian/dists/nightly/vivid/binary-amd64/Packages
12      ./debian/dists/nightly/vivid/binary-i386/Packages
12      ./debian/dists/nightly/wily/binary-amd64/Packages
12      ./debian/dists/nightly/wily/binary-i386/Packages
16      ./debian/dists/nightly/stretch/binary-amd64/Packages
16      ./debian/dists/nightly/stretch/binary-i386/Packages
20      ./debian/dists/nightly/sid/binary-amd64/Packages
20      ./debian/dists/nightly/sid/binary-i386/Packages

Is this the right place to report that? Who is in charge for debian packaging?

**Comment by stal888** [comment] 2016-04-14 18:06
@optimumtact

**Comment by optimumtact** [comment] 2016-04-14 21:03
Please note that only Debian (Sid, Jessie and Stretch) and Ubuntu (Vivid and Wily) are officially supported.

**Comment by optimumtact** [comment] 2016-04-14 21:04
This is mostly a side affect of having definitions for a lot more releases than we actually have packages for thanks to developer laziness.

**Comment by nurupo** [comment] 2016-09-05 05:38
You are seeing empty repos because the repo managing software was setup to handle a wild variety of environments in case we will provide pacakges for them, but we provide packages only for some subset of them. Currently we provide packages only for x86 and x86-64 architectures, Debian Jessie, Debian Stretch, Debian Sid, Ubuntu Vivid, Ubuntu Wily and Ubuntu Xenial distributions. If you limit it to just that, you will get 

```
12      nightly/xenial/binary-amd64/Packages
12      nightly/xenial/binary-i386/Packages
12      stable/jessie/binary-amd64/Packages
12      stable/jessie/binary-i386/Packages
12      stable/vivid/binary-amd64/Packages
12      stable/vivid/binary-i386/Packages
12      stable/wily/binary-amd64/Packages
12      stable/wily/binary-i386/Packages
12      stable/xenial/binary-amd64/Packages
12      stable/xenial/binary-i386/Packages
16      nightly/jessie/binary-amd64/Packages
16      nightly/jessie/binary-i386/Packages
16      nightly/vivid/binary-amd64/Packages
16      nightly/vivid/binary-i386/Packages
16      nightly/wily/binary-amd64/Packages
16      nightly/wily/binary-i386/Packages
20      nightly/sid/binary-amd64/Packages
20      nightly/sid/binary-i386/Packages
20      nightly/stretch/binary-amd64/Packages
20      nightly/stretch/binary-i386/Packages
20      stable/sid/binary-amd64/Packages
20      stable/sid/binary-i386/Packages
20      stable/stretch/binary-amd64/Packages
20      stable/stretch/binary-i386/Packages
```

The number doesn't necessarily mean that a distribution with larger number has more client available, while in same cases it's true, some clients were packaged only for some distributions and packaging them for other is an ongoing effort, the larger number generally means that for that distribution the packaging software we use automatically produced additional debug versions of the already present in the repo packages.

Anyway, these empty repos you see are not caused by some mistake, we in fact don't provide packages for them. Another question is whether you should be able to see all these repos? Probably not, so we will try changing our package managing software configuration to get rid of those empty repos in order to not confuse the users.

**Comment by nurupo** [comment] 2016-10-27 06:04
Closing the issue as the empty repos were removed.

**Closed by nurupo** 2016-10-27 06:04 UTC
